apiVersion: v1
kind: Service
metadata:
  name: yolo-inference-svc
spec:
  selector:
    app: yolo-inference
  type: NodePort
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
    nodePort: 30800 
